import type { Language, UiText } from './types';

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', dir: 'ltr' },
  { code: 'ar', name: 'العربية', dir: 'rtl' },
  { code: 'nl', name: 'Nederlands', dir: 'ltr' },
  { code: 'fr', name: 'Français', dir: 'ltr' },
  { code: 'es', name: 'Español', dir: 'ltr' },
];

export const STORY_THEMES = [
  { id: 'sci-fi-mystery', gradient: 'from-indigo-900 via-purple-900 to-slate-900' },
  { id: 'fantasy-quest', gradient: 'from-emerald-600 via-green-700 to-teal-800' },
  { id: 'cyberpunk-heist', gradient: 'from-fuchsia-600 via-pink-700 to-purple-800' },
  { id: 'haunted-mansion', gradient: 'from-slate-800 via-gray-900 to-black' },
  { id: 'desert-expedition', gradient: 'from-amber-500 via-orange-600 to-yellow-700' },
  { id: 'undersea-discovery', gradient: 'from-cyan-600 via-blue-700 to-indigo-800' },
  { id: 'steampunk-revolution', gradient: 'from-amber-800 via-stone-700 to-neutral-800' },
  { id: 'post-apocalyptic-survival', gradient: 'from-lime-900 via-neutral-800 to-stone-900' },
  { id: 'noir-detective', gradient: 'from-neutral-700 via-slate-800 to-gray-900' },
  { id: 'mythological-odyssey', gradient: 'from-yellow-300 via-amber-400 to-orange-500' },
  { id: 'time-travel-paradox', gradient: 'from-sky-500 via-violet-600 to-fuchsia-700' },
  { id: 'pirate-adventure', gradient: 'from-sky-700 via-teal-800 to-gray-900' },
  { id: 'spy-thriller', gradient: 'from-red-800 via-rose-900 to-black' },
  { id: 'western-showdown', gradient: 'from-orange-700 via-amber-800 to-stone-900' },
  { id: 'romance-story', gradient: 'from-rose-500 via-red-600 to-violet-700' },
  { id: 'viking-saga', gradient: 'from-blue-800 via-sky-900 to-slate-900' },
];

export const UI_TEXT: { [key: string]: UiText } = {
  en: {
    title: 'Nexus of Tales',
    subtitle: 'Your Adventure Awaits',
    chooseYourStory: 'Choose Your Story',
    loadingMessages: ['Weaving your fate...', 'Consulting the ancient oracles...', 'Plotting dastardly twists...', 'Polishing the hero\'s armor...', 'Generating a universe...'],
    errorMessage: 'An error occurred while crafting your story. Please try again.',
    tryAgain: 'Try Again',
    backToMenu: 'Back to Menu',
    playAgain: 'Play Again',
    theEnd: 'The End',
    themes: {
      'sci-fi-mystery': { title: 'Sci-Fi Mystery', description: 'An abandoned starship, a cryptic message. Uncover the truth before you become part of the void.' },
      'fantasy-quest': { title: 'Fantasy Quest', description: 'A dark prophecy, a legendary artifact, a kingdom to save. Your destiny is forged in magic and steel.' },
      'cyberpunk-heist': { title: 'Cyberpunk Heist', description: 'In a neon-drenched city, pull off the ultimate data heist against a world-owning mega-corporation.' },
      'haunted-mansion': { title: 'Haunted Mansion', description: 'Trapped inside a decaying manor, confront its vengeful spirits and escape before dawn.' },
      'desert-expedition': { title: 'Desert Expedition', description: 'Find a lost city of riches, but beware the ancient curse that protects it.' },
      'undersea-discovery': { title: 'Undersea Discovery', description: 'Pilot a submersible into the abyss to explore a trench hiding an impossible secret.' },
      'steampunk-revolution': { title: 'Steampunk Revolution', description: 'In a city of brass and steam, join the rebellion to overthrow a tyrannical regime.' },
      'post-apocalyptic-survival': { title: 'Post-Apocalyptic Survival', description: 'Navigate the ruins of a forgotten world. Every choice is a matter of life or death.' },
      'noir-detective': { title: 'Noir Detective', description: 'In a city of endless rain and secrets, solve a case that could cost you everything.' },
      'mythological-odyssey': { title: 'Mythological Odyssey', description: 'Embark on an epic journey to appease the gods and battle legendary beasts.' },
      'time-travel-paradox': { title: 'Time-Travel Paradox', description: 'A trip to the past has shattered the present. Can you fix the timeline before it collapses?' },
      'pirate-adventure': { title: 'Pirate Adventure', description: 'Seek legendary treasure on the high seas. Fortune or a watery grave awaits.' },
      'spy-thriller': { title: 'Spy Thriller', description: 'A web of deceit, a stolen secret. In the world of espionage, trust no one to survive.' },
      'western-showdown': { title: 'Western Showdown', description: 'A dusty town, a notorious outlaw, and a debt to be settled at high noon. Draw!' },
      'romance-story': { title: 'Romance Story', description: 'In a city of art and secrets, navigate a complex relationship where love and ambition collide.' },
      'viking-saga': { title: 'Viking Saga', description: 'Sail the icy seas, raid foreign shores, and earn your place in Valhalla among the gods.' },
    },
  },
  ar: {
    title: 'ملتقى الحكايات',
    subtitle: 'مغامرتك تنتظرك',
    chooseYourStory: 'اختر حكايتك',
    loadingMessages: ['ننسج قدرك...', 'استشارة الأوراكل القديمة...', 'التخطيط للتحولات الغادرة...', 'صقل درع البطل...', 'توليد عالم...'],
    errorMessage: 'حدث خطأ أثناء صياغة قصتك. الرجاء معاودة المحاولة.',
    tryAgain: 'حاول مرة أخرى',
    backToMenu: 'العودة للقائمة',
    playAgain: 'العب مرة أخرى',
    theEnd: 'النهاية',
    themes: {
      'sci-fi-mystery': { title: 'غموض الخيال العلمي', description: 'سفينة فضاء مهجورة، رسالة غامضة. اكشف الحقيقة قبل أن تصبح جزءًا من الفراغ.' },
      'fantasy-quest': { title: 'مهمة خيالية', description: 'نبوءة مظلمة، قطعة أثرية أسطورية، مملكة لإنقاذها. مصيرك يصنع بالسحر والفولاذ.' },
      'cyberpunk-heist': { title: 'سرقة سايبربانك', description: 'في مدينة غارقة بالنيون، نفذ أكبر سرقة بيانات ضد شركة عملاقة تملك العالم.' },
      'haunted-mansion': { title: 'القصر المسكون', description: 'عالق داخل قصر متداعٍ، واجه أشباحه المنتقمة واهرب قبل الفجر.' },
      'desert-expedition': { title: 'رحلة صحراوية', description: 'اعثر على مدينة الثروات المفقودة، لكن احذر من اللعنة القديمة التي تحميها.' },
      'undersea-discovery': { title: 'اكتشاف تحت سطح البحر', description: 'قد غواصة إلى الهاوية لاستكشاف خندق يخفي سرًا مستحيلًا.' },
      'steampunk-revolution': { title: 'ثورة الستيم بانك', description: 'في مدينة من النحاس والبخار، انضم إلى الثورة للإطاحة بنظام استبدادي.' },
      'post-apocalyptic-survival': { title: 'بقاء ما بعد الكارثة', description: 'تجول في أنقاض عالم منسي. كل خيار هو مسألة حياة أو موت.' },
      'noir-detective': { title: 'محقق نوار', description: 'في مدينة المطر والأسرار التي لا تنتهي، قم بحل قضية قد تكلفك كل شيء.' },
      'mythological-odyssey': { title: 'ملحمة أسطورية', description: 'انطلق في رحلة ملحمية لإرضاء الآلهة ومحاربة الوحوش الأسطورية.' },
      'time-travel-paradox': { title: 'مفارقة السفر عبر الزمن', description: 'رحلة واحدة إلى الماضي حطمت الحاضر. هل يمكنك إصلاح الخط الزمني قبل أن ينهار؟' },
      'pirate-adventure': { title: 'مغامرة القراصنة', description: 'ارفع الأشرعة وابحث عن الكنز الأسطوري في البحار الغادرة. الثروة أو قبر مائي في انتظارك.' },
      'spy-thriller': { title: 'جاسوسية مثيرة', description: 'شبكة من الخداع، سر مسروق. في عالم الجاسوسية، لا تثق بأحد للبقاء على قيد الحياة.' },
      'western-showdown': { title: 'مواجهة الغرب', description: 'بلدة مغبرة، خارج عن القانون سيئ السمعة، ودين يجب تسويته عند الظهيرة. اسحب!' },
      'romance-story': { title: 'قصة رومانسية', description: 'في مدينة الفن والأسرار، خض علاقة معقدة حيث يتصادم الحب والطموح.' },
      'viking-saga': { title: 'ملحمة الفايكنج', description: 'أبحر في البحار الجليدية، أغر على الشواطئ الأجنبية، واكسب مكانك في فالهالا بين الآلهة.' },
    },
  },
  nl: {
    title: 'Nexus van Verhalen',
    subtitle: 'Jouw Avontuur Wacht',
    chooseYourStory: 'Kies Je Verhaal',
    loadingMessages: ['Je lot wordt geweven...', 'De oude orakels raadplegen...', 'Duivelse wendingen plotten...', 'Het harnas van de held polijsten...', 'Een universum genereren...'],
    errorMessage: 'Er is een fout opgetreden. Probeer het opnieuw.',
    tryAgain: 'Probeer Opnieuw',
    backToMenu: 'Terug naar Menu',
    playAgain: 'Speel Opnieuw',
    theEnd: 'Het Einde',
    themes: {
        'sci-fi-mystery': { title: 'Sci-Fi Mysterie', description: 'Een verlaten ruimteschip, een cryptisch bericht. Onthul de waarheid voordat je deel wordt van de leegte.' },
        'fantasy-quest': { title: 'Fantasie Zoektocht', description: 'Een duistere profetie, een legendarisch artefact, een koninkrijk om te redden. Je lot wordt gesmeed in magie en staal.' },
        'cyberpunk-heist': { title: 'Cyberpunk Overval', description: 'Voer in een neon-overgoten stad de ultieme data-overval uit op een mega-corporatie die de wereld bezit.' },
        'haunted-mansion': { title: 'Spookhuis', description: 'Gevangen in een vervallen landhuis, confronteer de wraakzuchtige geesten en ontsnap voor zonsopgang.' },
        'desert-expedition': { title: 'Woestijn Expeditie', description: 'Vind een verloren stad vol rijkdom, maar pas op voor de oude vloek die haar beschermt.' },
        'undersea-discovery': { title: 'Onderzeese Ontdekking', description: 'Bestuur een duikboot in de afgrond om een geul te verkennen die een onmogelijk geheim verbergt.' },
        'steampunk-revolution': { title: 'Steampunk Revolutie', description: 'Sluit je in een stad van koper en stoom aan bij de opstand om een tiranniek regime omver te werpen.' },
        'post-apocalyptic-survival': { title: 'Post-Apocalyptische Overleving', description: 'Navigeer door de ruïnes van een vergeten wereld. Elke keuze is een kwestie van leven of dood.' },
        'noir-detective': { title: 'Noir Detective', description: 'Los in een stad van eindeloze regen en geheimen een zaak op die je alles kan kosten.' },
        'mythological-odyssey': { title: 'Mythologische Odyssee', description: 'Begin aan een epische reis om de goden te sussen en legendarische beesten te bestrijden.' },
        'time-travel-paradox': { title: 'Tijdreisparadox', description: 'Een reis naar het verleden heeft het heden verbrijzeld. Kun jij de tijdlijn repareren?' },
        'pirate-adventure': { title: 'Piratenavontuur', description: 'Hijs de zeilen en zoek naar legendarische schatten. Fortuin of een watergraf wacht.' },
        'spy-thriller': { title: 'Spionagethriller', description: 'Een web van bedrog, een gestolen geheim. Vertrouw niemand om te overleven in de wereld van spionage.' },
        'western-showdown': { title: 'Westerse Confrontatie', description: 'Een stoffig stadje, een beruchte outlaw, en een schuld die om twaalf uur \'s middags vereffend moet worden. Trek!' },
        'romance-story': { title: 'Romantisch Verhaal', description: 'Navigeer in een stad van kunst en geheimen een complexe relatie waar liefde en ambitie botsen.' },
        'viking-saga': { title: 'Viking Saga', description: 'Bezeil de ijzige zeeën, plunder vreemde kusten en verdien je plaats in Walhalla tussen de goden.' },
    },
  },
  fr: {
    title: 'Nexus des Contes',
    subtitle: 'Votre Aventure Vous Attend',
    chooseYourStory: 'Choisissez Votre Histoire',
    loadingMessages: ['Tissage de votre destin...', 'Consultation des anciens oracles...', 'Comploter des rebondissements ignobles...', 'Polir l\'armure du héros...', 'Génération d\'un univers...'],
    errorMessage: "Une erreur est survenue. Veuillez réessayer.",
    tryAgain: 'Réessayer',
    backToMenu: 'Retour au Menu',
    playAgain: 'Rejouer',
    theEnd: 'Fin',
    themes: {
        'sci-fi-mystery': { title: 'Mystère de Science-Fiction', description: 'Un vaisseau abandonné, un message cryptique. Découvrez la vérité avant de faire partie du vide.' },
        'fantasy-quest': { title: 'Quête Fantastique', description: 'Une sombre prophétie, un artefact légendaire, un royaume à sauver. Votre destin est forgé dans la magie et l\'acier.' },
        'cyberpunk-heist': { title: 'Casse Cyberpunk', description: 'Dans une ville inondée de néons, réalisez le casse de données ultime contre une méga-corporation.' },
        'haunted-mansion': { title: 'Manoir Hanté', description: 'Piégé dans un manoir délabré, affrontez ses esprits vengeurs et échappez-vous avant l\'aube.' },
        'desert-expedition': { title: 'Expédition dans le Désert', description: 'Trouvez une cité perdue de richesses, mais méfiez-vous de l\'ancienne malédiction qui la protège.' },
        'undersea-discovery': { title: 'Découverte Sous-Marine', description: 'Pilotez un submersible dans l\'abîme pour explorer une fosse cachant un secret impossible.' },
        'steampunk-revolution': { title: 'Révolution Steampunk', description: 'Dans une ville de laiton et de vapeur, rejoignez la rébellion pour renverser un régime tyrannique.' },
        'post-apocalyptic-survival': { title: 'Survie Post-Apocalyptique', description: 'Naviguez dans les ruines d\'un monde oublié. Chaque choix est une question de vie ou de mort.' },
        'noir-detective': { title: 'Détective Noir', description: 'Dans une ville de pluie et de secrets, résolvez une affaire qui pourrait tout vous coûter.' },
        'mythological-odyssey': { title: 'Odyssée Mythologique', description: 'Embarquez pour un voyage épique pour apaiser les dieux et combattre des bêtes légendaires.' },
        'time-travel-paradox': { title: 'Paradoxe Temporel', description: 'Un voyage dans le passé a brisé le présent. Pouvez-vous réparer la chronologie?' },
        'pirate-adventure': { title: 'Aventure de Pirate', description: 'Hissez les voiles et cherchez un trésor légendaire. La fortune ou une tombe aquatique vous attend.' },
        'spy-thriller': { title: 'Thriller d\'Espionnage', description: 'Un réseau de tromperies, un secret volé. Dans le monde de l\'espionnage, ne faites confiance à personne pour survivre.' },
        'western-showdown': { title: 'Confrontation Western', description: 'Une ville poussiéreuse, un hors-la-loi notoire, et une dette à régler à midi. Dégainez !' },
        'romance-story': { title: 'Histoire Romantique', description: 'Dans une ville d\'art et de secrets, naviguez dans une relation complexe où l\'amour et l\'ambition s\'affrontent.' },
        'viking-saga': { title: 'Saga Viking', description: 'Naviguez sur les mers glacées, pillez les rivages étrangers et gagnez votre place au Valhalla parmi les dieux.' },
    },
  },
  es: {
    title: 'Nexo de Relatos',
    subtitle: 'Tu Aventura te Espera',
    chooseYourStory: 'Elige Tu Historia',
    loadingMessages: ['Tejiendo tu destino...', 'Consultando a los antiguos oráculos...', 'Tramando giros malvados...', 'Puliendo la armadura del héroe...', 'Generando un universo...'],
    errorMessage: 'Ocurrió un error. Por favor, inténtalo de nuevo.',
    tryAgain: 'Intentar de Nuevo',
    backToMenu: 'Volver al Menú',
    playAgain: 'Jugar de Nuevo',
    theEnd: 'Fin',
    themes: {
        'sci-fi-mystery': { title: 'Misterio de Ciencia Ficción', description: 'Una nave abandonada, un mensaje críptico. Descubre la verdad antes de ser parte del vacío.' },
        'fantasy-quest': { title: 'Búsqueda de Fantasía', description: 'Una profecía oscura, un artefacto legendario, un reino que salvar. Tu destino se forja en magia y acero.' },
        'cyberpunk-heist': { title: 'Atraco Cyberpunk', description: 'En una ciudad bañada en neón, realiza el atraco de datos definitivo contra una megacorporación.' },
        'haunted-mansion': { title: 'Mansión Encantada', description: 'Atrapado en una mansión en ruinas, enfréntate a sus espíritus vengativos y escapa antes del amanecer.' },
        'desert-expedition': { title: 'Expedición en el Desierto', description: 'Encuentra una ciudad perdida de riquezas, pero cuidado con la antigua maldición que la protege.' },
        'undersea-discovery': { title: 'Descubrimiento Submarino', description: 'Pilota un sumergible al abismo para explorar una fosa que esconde un secreto imposible.' },
        'steampunk-revolution': { title: 'Revolución Steampunk', description: 'En una ciudad de latón y vapor, únete a la rebelión para derrocar un régimen tiránico.' },
        'post-apocalyptic-survival': { title: 'Supervivencia Post-Apocalíptica', description: 'Navega por las ruinas de un mundo olvidado. Cada elección es una cuestión de vida o de muerte.' },
        'noir-detective': { title: 'Detective Noir', description: 'En una ciudad de lluvia y secretos, resuelve un caso que podría costarte todo.' },
        'mythological-odyssey': { title: 'Odisea Mitológica', description: 'Embárcate en un viaje épico para apaciguar a los dioses y luchar contra bestias legendarias.' },
        'time-travel-paradox': { title: 'Paradoja del Viaje en el Tiempo', description: 'Un viaje al pasado ha destrozado el presente. ¿Puedes arreglar la línea de tiempo?' },
        'pirate-adventure': { title: 'Aventura Pirata', description: 'Iza las velas y busca tesoros legendarios. La fortuna o una tumba acuática te espera.' },
        'spy-thriller': { title: 'Thriller de Espías', description: 'Una red de engaños, un secreto robado. En el mundo del espionaje, no confíes en nadie para sobrevivir.' },
        'western-showdown': { title: 'Duelo en el Oeste', description: 'Un pueblo polvoriento, un forajido notorio y una deuda que saldar al mediodía. ¡Desenfundar!' },
        'romance-story': { title: 'Historia Romántica', description: 'En una ciudad de arte y secretos, navega una relación compleja donde el amor y la ambición chocan.' },
        'viking-saga': { title: 'Saga Vikinga', description: 'Navega por los mares helados, saquea costas extrañas y gánate tu lugar en el Valhalla entre los dioses.' },
    },
  },
};